import { json } from '@sveltejs/kit';

const mobileTop100 = [
	'Candy Crush Saga',
	'Subway Surfers',
	'Honor of Kings',
	'Roblox',
	'PUBG Mobile',
	'Free Fire',
	'Monopoly GO!',
	'Royal Match',
	'Coin Master',
	'Clash of Clans',
	'Pokémon GO',
	'Brawl Stars',
	'Clash Royale',
	'Genshin Impact',
	'Call of Duty: Mobile',
	'Gardenscapes',
	'Homescapes',
	'8 Ball Pool',
	'Ludo King',
	'Block Blast!',
	'Fishdom',
	'Township',
	'Stumble Guys',
	'Among Us',
	'Mobile Legends: Bang Bang',
	'Hay Day',
	'Hill Climb Racing',
	'Hill Climb Racing 2',
	'Pou',
	'Temple Run 2',
	'Minion Rush',
	'Angry Birds 2',
	'Jetpack Joyride',
	'Dragon Ball Legends',
	'Asphalt 9: Legends',
	'Real Racing 3',
	'Mario Kart Tour',
	'Dream League Soccer',
	'FIFA Mobile',
	'eFootball™',
	'World of Tanks Blitz',
	'RAID: Shadow Legends',
	'Summoners War',
	'AFK Arena',
	'Arknights',
	'Honkai: Star Rail',
	'Honkai Impact 3rd',
	'Fate/Grand Order',
	'Uma Musume Pretty Derby',
	'Dislyte',
	'Idle Heroes',
	'Empires & Puzzles',
	'Rise of Kingdoms',
	'Lords Mobile',
	'State of Survival',
	'Last War: Survival',
	'Whiteout Survival',
	'Evony: The King’s Return',
	'Doomsday: Last Survivors',
	'Warpath',
	'Clash of Lords 2',
	'Match Masters',
	'Toon Blast',
	'Lily’s Garden',
	'Project Makeover',
	'Words With Friends 2',
	'Scrabble GO',
	'Wordscapes',
	'Brain Test: Tricky Puzzles',
	'Cut the Rope',
	'Where’s My Water?',
	'My Talking Tom',
	'My Talking Angela 2',
	'Talking Tom Gold Run',
	'PK XD',
	'Rec Room',
	'Brawlhalla',
	'Minecraft',
	'League of Legends: Wild Rift',
	'Legends of Runeterra',
	'MARVEL Snap',
	'Hearthstone',
	'Shadow Fight 3',
	'Shadow Fight 4: Arena',
	'Dead Trigger 2',
	'Into the Dead 2',
	'Zombie Tsunami',
	'Plants vs. Zombies 2',
	'Geometry Dash Lite',
	'Crossy Road',
	'Sky: Children of the Light',
	'Cookie Run: Kingdom',
	'Blue Archive',
	'NIKKE',
	'Azur Lane',
	'Fire Emblem Heroes',
	'Discord Game SDK Demo',
	'Arena Breakout',
	'CarX Drift Racing 2',
	'MadOut2 BigCityOnline',
	'Bingo Blitz'
];

export function GET() {
	const games = mobileTop100.slice(0, 100).map((name, index) => ({
		id: index + 1,
		name,
		rank: index + 1,
		popularityScore: 101 - (index + 1)
	}));

	return json({ games });
}
